"""Build the embedded PTX using NVIDIA NVRTC, without a runtime DLL dependency.

Usage: python tools/compile_cuda.py --nvrtc ABSOLUTE_PATH_TO_NVRTC_DLL
The generated header is checked in so normal MSVC builds need no CUDA Toolkit.
"""
import argparse
import ctypes as c
import hashlib
import json
import os
from pathlib import Path

ap=argparse.ArgumentParser()
ap.add_argument('--nvrtc',type=Path,required=True)
args=ap.parse_args()
root=Path(__file__).resolve().parents[1]
source=root/'src/color/ColorKernel.cu'
directory=os.add_dll_directory(str(args.nvrtc.resolve().parent))
builtins=[c.WinDLL(str(p.resolve())) for p in args.nvrtc.parent.glob('nvrtc-builtins64_128.dll')]
nv=c.WinDLL(str(args.nvrtc.resolve()))
nv.nvrtcCreateProgram.argtypes=[c.POINTER(c.c_void_p),c.c_char_p,c.c_char_p,c.c_int,c.c_void_p,c.c_void_p]
nv.nvrtcCompileProgram.argtypes=[c.c_void_p,c.c_int,c.POINTER(c.c_char_p)]
for name in ('nvrtcGetPTXSize','nvrtcGetProgramLogSize'):
    getattr(nv,name).argtypes=[c.c_void_p,c.POINTER(c.c_size_t)]
for name in ('nvrtcGetPTX','nvrtcGetProgramLog'):
    getattr(nv,name).argtypes=[c.c_void_p,c.c_void_p]
nv.nvrtcDestroyProgram.argtypes=[c.POINTER(c.c_void_p)]
options=['--std=c++17','--gpu-architecture=compute_75','--fmad=false','--ftz=false','--prec-div=true','--prec-sqrt=true']
program=c.c_void_p()
assert nv.nvrtcCreateProgram(c.byref(program),source.read_text(encoding='utf-8').encode(),b'ColorKernel.cu',0,None,None)==0
try:
    result=nv.nvrtcCompileProgram(program,len(options),(c.c_char_p*len(options))(*(s.encode() for s in options)))
    size=c.c_size_t();nv.nvrtcGetProgramLogSize(program,c.byref(size))
    log=c.create_string_buffer(size.value);nv.nvrtcGetProgramLog(program,log)
    print(log.value.decode())
    if result: raise RuntimeError(f'NVRTC compilation error {result}')
    nv.nvrtcGetPTXSize(program,c.byref(size))
    ptx=c.create_string_buffer(size.value);assert nv.nvrtcGetPTX(program,ptx)==0
    major=c.c_int();minor=c.c_int();nv.nvrtcVersion(c.byref(major),c.byref(minor))
    data=ptx.value+b'\0'
    body='\n'.join(','.join(str(x) for x in data[i:i+32])+',' for i in range(0,len(data),32))
    (root/'src/color/ColorKernel.ptx.h').write_text('// Generated by tools/compile_cuda.py. Do not edit.\n#pragma once\ninline constexpr unsigned char ColorPTX[]={\n'+body+'\n};\n',encoding='utf-8')
    manifest={'source_sha256':hashlib.sha256(source.read_text(encoding='utf-8').encode()).hexdigest(),'ptx_sha256':hashlib.sha256(ptx.value).hexdigest(),
              'nvrtc_version':f'{major.value}.{minor.value}','compiler_sha256':hashlib.sha256(args.nvrtc.read_bytes()).hexdigest(),'options':options}
    (root/'src/color/ColorKernel.manifest.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    print(json.dumps(manifest,indent=2))
finally:
    nv.nvrtcDestroyProgram(c.byref(program))
